Add template inheritance spec
mustache/spec pull request #75
Opened 2014-04-14 21:07 UTC by jazzdan

This adds a specification for [hogan.js](https://github.com/twitter/hogan.js) style template inheritance. As of time of writing, three mustache implementations are 100% compatible with this implementation:
- [hogan.js](https://github.com/twitter/hogan.js)
- [mustache.php](https://github.com/bobthecow/mustache.php/pull/198)
- [mustache.java](https://github.com/spullara/mustache.java)
- [GRMustache](https://github.com/groue/GRMustache) (thanks @groue!)

Here's how it works:

``` HTML+Django
{{! header.mustache }}
<head>
  <title>{{$title}}Default title{{/title}}</title>
</head>
```

``` HTML+Django
{{! base.mustache }}
<html>
  {{$header}}{{/header}}
  {{$content}}{{/content}}
</html>
```

``` HTML+Django
{{! mypage.mustache }}
{{<base}}
  {{$header}}
    {{<header}}
      {{$title}}My page title{{/title}}
    {{/header}}
  {{/header}}

  {{$content}}
    <h1>Hello world</h1>
  {{/content}}
{{/base}}
```

Rendering mypage.mustache would output:

``` HTML
<html><head><title>My page title</title></head><h1>Hello world</h1></html>
```

A full specification can be seen below.

At @Etsy, much like @Twitter (see #38), we often want to have one template where we maintain the "bones" of the page and each real page on the site merely replaces sections of that page with appropriate content. A simple example of this can be seen above, where a page can grab base, getting all of our analytics scripts and other markup that every page needs, while retaining the ability to swap in a completely different header. Alternatives, such as copying the bones to every top level template, or simulating this behavior with a multi-step mustache render on the server, are not ideal.

Etsy is in the process of rolling out the new version of mustache.php that supports template inheritance to our production cluster after testing this implementation extensively. Hogan.js and mustache.java are both being used in production at Twitter.

Many thanks to @dtb, @mdg, @bobthecow for their assistance. Special thanks to @spullara for quickly making mustache.java compatible with this spec.

2016-04-04 20:05 UTC, nadako commented
I just added support for this in [hxmustache](https://github.com/nadako/hxmustache). It passes all spec tests.

2016-09-08 06:48 UTC, Danappelxx commented
My Swift implementation, [MuttonChop](https://github.com/Danappelxx/MuttonChop), also just implemented template inheritance (conforming to this spec). Maybe its time to push for Mustache v2 and make this official?

2018-10-14 06:03 UTC, bubach commented
Wow, I really dislike this concept - why would you ever want to do this?  I mean, it's not only way cleaner but also makes way more sense to implement some sort of page-tree with nested View-objects based on request parameters and or config.  Seems like a bad solution to a non existing problem.

2020-04-29 13:03 UTC, bennofs commented
This is quite old, does it have any chance to become merged in the future? Or has spec development stopped?

2020-04-29 17:07 UTC, spullara commented
Many implementations have it so it is defacto in the specification. I don't think they have updated the spec itself though in a very long time.

2020-12-29 13:32 UTC, gasche commented
When a parameter block passed to a parent contains tags, should those tags be interpreted in the current context, or in the context of the block tag use-site within the parent? I looked for a mention of this in the specification, but found none. What do current implementations do?

Consider (in the syntax of spec tests):

```
data: { include-site: { place: "include site"}, use-site: { place: "use site"} }
template: |
  {{#include-site}}
    {{<include}}
      {{$var}}evaluated at {{place}}{{/var}}
    {{/include}}
  {{/include-site}
partials:
  include: |
    {{#use-site}}
      {{$var}}default{{/var}}
    {{/use-site}}
```

Should we expect `evaluated at include site` or `evaluated at use site`?

2020-12-29 13:51 UTC, gasche commented
> What do current implementations do?

I found a first answer [in the mustache.php testsuite](https://github.com/bobthecow/mustache.php/blob/master/test/Mustache/Test/Functional/InheritanceTest.php#L471-L486): for mustache.php, parameters should be evaluated lazily, in the context of the parent template.

```
    public function testInheritanceWithLazyEvaluation()
    {
        $partials = array(
            'parent' => '{{#items}}{{$value}}ignored{{/value}}{{/items}}',
        );

        $this->mustache->setPartials($partials);

        $tpl = $this->mustache->loadTemplate(
            '{{<parent}}{{$value}}<{{ . }}>{{/value}}{{/parent}}'
        );

        $data = array('items' => array(1, 2, 3));

        $this->assertEquals('<1><2><3>', $tpl->render($data));
    }
```

I wish this was made explicit in the specification -- assuming that other implementations made consistent choices.

2020-12-29 15:05 UTC, gasche commented
Here is a more up-to-date list of Mustache implementations that support this extension:

- [hogan.js](https://github.com/twitter/hogan.js)
- [mustache.php](https://github.com/bobthecow/mustache.php)
- [mustache.java](https://github.com/spullara/mustache.java)
- [GRMustache](https://github.com/groue/GRMustache) (Obj-C) and [GRMustache.swift](https://github.com/groue/GRMustache.swift) (Swift)
- [Text::Caml](https://github.com/vti/text-caml) (Perl)
- [hxmustache](https://github.com/nadako/hxmustache) (Haxe)
- [MuttonChop](https://github.com/Danappelxx/MuttonChop) (Swift)

2021-03-09 19:22 UTC, jgonggrijp requested changes
This is a really old PR and I'm a bit of an outsider since I only just wrote my own Mustache implementation, but I figured a review might still be useful since this PR hasn't been merged yet and I might offer a "fresh perspective" as a newcomer. For clarity, my own implementation doesn't support this spec yet, but I do want to support it.

Semantically and syntactically speaking, I'm perfectly happy with the spec as-is, and I agree that it should be merged in v2. The fact that it is already existing practice in multiple implementations also makes the case for this spec stronger in my opinion. I would however propose to make two superficial (but important) changes:

1. Change the spec name from `inheritance.yml` to `~inheritance.yml` to mark it as an optional module. It complicates the implementation a bit, so it might deter new implementers otherwise. **Edit to add:** after https://github.com/mustache/spec/pull/75#issuecomment-799373971, I would suggest `~parametric-partial.yml` instead.
2. Make the jargon much more consistent. I found `{{$block}}` being referred to as "block", "parameter" and "substitution" and `{{<parent}}` as "parent", "super", "include" and even "partial". ~Especially "partial" should really be avoided in my opinion, as it is needlessly confusing.~ I started to make change suggestions for the incorrect appearances of "partial", but I didn't go all the way through. I would suggest using ~only "parent" or "super" for `{{<parent}}` and~ "parameter block" for `{{$block}}` when used by itself or "argument block" when used inside `{{<parent}}...{{/parent}}`.. **Edit to add:** I changed my opinion about this and I now believe that "parent", "super" and "inheritance" are actually the words that should be avoided. See https://github.com/mustache/spec/pull/75#issuecomment-799373971.

Some other remarks/observations:

- I'm in favor of specifying that interpolation and section tags inside argument blocks should be evaluated in the context of the parent template, as proposed by @gasche in https://github.com/mustache/spec/pull/75#issuecomment-752081510 after finding that this is the existing practice in mustache.php. This makes it possible to implement inheritance by inlining the parent template, making precompiled templates potentially faster. It is also more consistent with the same paths already occurring inside the parameter block default in the parent template.
- I really like the chosen sigils/indicators/whathever they are called. `<` makes sense because in a way, it is dual to the `>` for partials. `$` makes sense because the character is used for variable names or parameter expansions in several programming languages.
- Maybe it would be an option to open a "future" branch so that changes for v2 can already be merged into the repository?

2021-03-09 21:49 UTC, gasche commented
Thanks for the carefully worded message! I agree that it's nice to push this further: I think that with the amount of implementations that support the feature, it's a bit silly to refer to it as a PR to the original spec.

> Semantically and syntactically speaking, I'm perfectly happy with the spec as-is, and I agree that it should be merged in v2. [...]
> 
>     1. Change the spec name from `inheritance.yml` to `~inheritance.yml` to mark it as an optional module. It complicates the implementation a bit, so it might deter new implementers otherwise.

If this is made an optional part of the spec, does it need to correspond to a major-version bump for the specification? I haven't thought hard about the versioning scheme but I would think as adding optional aspects as a backward-compatibility-preserving changes (implementations remain compliant). (One exception would be an implementation that provides a feature using the same syntax as proposed here but with different semantics, then I guess it would become non-compliant?)

>     2. Make the jargon much more consistent. I found `{{$block}}` being referred to as "block", "parameter" and "substitution" and `{{<parent}}` as "parent", "super", "include" and even "partial". Especially "partial" should really be avoided in my opinion, as it is needlessly confusing. I started to make change suggestions for the incorrect appearances of "partial", but I didn't go all the way through. I would suggest using only "parent" or "super" for `{{<parent}}` and "parameter block" for `{{$block}}` when used by itself or "argument block" when used inside `{{<parent}}...{{/parent}}`..

I agree that the terminology could be made more consistent. I myself use `parameter block` for `{{$foo}}...{{/foo}}` (the "block" part is important because it's not just a tag, it can contain an arbitrary sub-template), and sometimes just "parameter" when the context makes it very clear. I think that "block" means generically anything with an opening and a closing form (usually `{{/foo}}`) and stuff in the middle.

Regarding the whole feature or `{{<foo}}`, I personally use the wording "partial with parameters": it behaves exactly like partials `{{>foo}}` (it expands to a sub-template), except it can take parameters. This is a wording that makes sense to my community (more oriented towards functional programming than oo-style inheritance), but then it is not perfect either because the shadowing semantics of partial blocks are unintuitive if you think of them as function calls (the outermost definition wins, not the innermost one as one would expect). I guess I mean that I haven't found a perfect name for this part of the feature, and we should be prepared for different terminologies to survive.

Another remark: upon implementing the feature I found that it shows the limits of the current way whitespace is handled in Mustache (the notion of standalone tags, and the indentation of partials). Ideally the user would want:
- `{{$foo}}...{{/foo}}` to count as a single "standalone tag" if it is surrounded by whitespace
- the indentation of the parameter block to be *substracted* at rendering time, instead of being added like the indentation of a partial (with or without parameters)
- the way we count indentation to be slightly different when `{{$foo}}` is on its own line and the comment following is indented.

Long story short, I went down a rabbit hole of finding better specifications for whitespace handling in Mustache, and they tended to be more complex, more natural for the user, and incompatible with existing implementations / the spec. in corner cases. I gave up and went back to something mostly-standard (my implementation does substract the indentation of the parameter block, iirc.), but it remains a (minor) sticking point with the feature and its specification.

2021-03-10 03:36 UTC, jgonggrijp commented
Good point about "partials without parameters" and "partials with parameters". I now realize they are more similar than I thought, and also that the implementation can probably be more similar than I thought.

> If this is made an optional part of the spec, does it need to correspond to a major-version bump for the specification? I haven't thought hard about the versioning scheme but I would think as adding optional aspects as a backward-compatibility-preserving changes (implementations remain compliant). (One exception would be an implementation that provides a feature using the same syntax as proposed here but with different semantics, then I guess it would become non-compliant?)

I was thinking along these lines, too, but I didn't dare write it down. I'm glad you did. With it being an optional module, I feel it could be a minor version bump.

2021-03-15 12:18 UTC, jgonggrijp commented
Since my review and previous comment, I have radically changed my opinion about jargon consistency. I now believe that "parent" and "inheritance" are the needlessly confusing words that should be avoided. The thing we're talking about here is just a parametric partial. Thanks to @gasche for making me realize this.

2021-03-15 12:24 UTC, jgonggrijp commented on specs/inheritance.yml
> +    expected: "test override"
I retract the above comment.

2021-03-15 12:24 UTC, jgonggrijp commented on specs/inheritance.yml
> +    desc: Two overridden partials with different content
I retract the above comment.

2021-03-15 12:24 UTC, jgonggrijp commented on specs/inheritance.yml
> +    desc: Inherit indentation when overriding a partial
I retract the above comment.

2021-03-15 12:24 UTC, jgonggrijp commented on specs/inheritance.yml
> +    desc: Override partial with newlines
I retract the above comment.

2021-03-15 13:02 UTC, jgonggrijp commented
@gasche 

> Another remark: upon implementing the feature I found that it shows the limits of the current way whitespace is handled in Mustache (the notion of standalone tags, and the indentation of partials). Ideally the user would want:
> 
> * `{{$foo}}...{{/foo}}` to count as a single "standalone tag" if it is surrounded by whitespace

Could you elaborate on this? The way I've understood standalone tags so far, it just means that a single tag that is all alone on a line shouldn't leave a blank line in the output, i.e.,

```mustache
{{!comment}}
foo
{{#section}}
    content
{{/section}}
```

should produce

```
foo
    content
```

(assuming that `section` is truthy) rather than

```

foo

    content

```

. Given this interpretation, I have no imagination of what it would even mean for a parameter block as a whole to count as a standalone tag. Consider the following example:

```mustache
foo
    {{$parameter}}content{{/parameter}}
bar
```

What do you believe should happen? Surely not that the entire line containing `content` should be removed from the output?

> * the indentation of the parameter block to be _substracted_ at rendering time, instead of being added like the indentation of a partial (with or without parameters)
> * the way we count indentation to be slightly different when `{{$foo}}` is on its own line and the comment following is indented.

If you mean that

```mustache
{{!partial.mustache}}
foo
    bar
    {{$parameter1}}baz{{/parameter1}}
    {{$parameter2}}foobar{{/parameter2}}

{{!template.mustache}}
foobaz
    barbaz
    {{<partial}}
        foofoo
            {{$parameter1}}barbar{{/parameter1}}
      {{$parameter2}}
          bazbaz
      {{/parameter2}}
    {{/partial}}
```

should output

```
foobaz
    barbaz
    foo
        bar
        barbar
            bazbaz
```

then I think I agree with you.

> 
> Long story short, I went down a rabbit hole of finding better specifications for whitespace handling in Mustache, and they tended to be more complex, more natural for the user, and incompatible with existing implementations / the spec. in corner cases. I gave up and went back to something mostly-standard (my implementation does substract the indentation of the parameter block, iirc.), but it remains a (minor) sticking point with the feature and its specification.

Does this really need to be fully specified before merging, though? I think the existing spec is worthwhile as-is, even if it leaves some freedom to implementers with regard to whitespace handling.

2021-03-19 07:41 UTC, gasche commented
Regarding the terminology: I would be a bit careful here, to accommodate several viewpoints. I think that to some people thinking of those new partials as "functions with parameters" will be most helpful, but some other would be familiar with the "object-oriented inheritance" view. We could have a description that mentions both views, and I think we could manage to consistently/clearly use two terminologies.

Note that the two notions are not completely equivalent in what semantics they suggest: in case of shadowing (two nested partial-with-parameters define parameters of the same name), the function view would suggest that the innermost definition (the callee) should override the outermost one, while the inheritance view suggests that the outermost definition (the parent class) should override the innermost one; and it is that latter view that was chosen (possibly without realizing the choice) in the original implementation of partial-with-parameters, and followed by further implementations.

2021-03-19 08:00 UTC, gasche commented
Regarding whitespace: I think that, ideally

```
  {{<foo}}{{$param}}bar{{/param}}{{/foo}}
```

and 

```
  {{<foo}}
    {{$param}}bar{{/param}}
  {{/foo}}
```

should result in the same printing. However, with the current notion of "standalone" tag, then `{{<foo}}` is standalone in the second example but *not* in the first one. This suggests that the second example should *not* include the newlines following `{{>foo}}` or `{{/foo}}` in the second example, but according to our current specification it probably should in the first example.

I think that a better concept of whitespace handling should be about whether templating constructs (dynamically) emit "visible" content on the current line, or they don't. If a "standalone" construct (not `{{foo}}`, which counts as visible even when it emits whitespace only) is on a line without any visible content, then the whitespace before it is treated as indentation and the whitespace after it is elided from the output. With this definition, the use of parameter blocks as *definition* site is clearly not visible, and so both examples should elide the newline. But (1) this is a significant change compared to the current definition and in some cases it changes behavior (for example it makes `{{#foo}}{{#bar}}` act as a standalone sequence of tokens, which is nice but incompatible), and (2) I don't know how difficult it would be to implement for other Mustache implementations (I implemented this in a prototype as an experiment).

> Does this really need to be fully specified before merging, though? I think the existing spec is worthwhile as-is, even if it leaves some freedom to implementers with regard to whitespace handling.

No, I think that this *does not* need to be fully specified before merging, and adding that requirement could be fatal to this PR who already had a long and unsatisfying life. My personal opinion is that this specification should be merged (marked optional) in the specification, to accept the current status that it *is* consensual among implementations, and largely implemented. It is a de-facto (optional) standard, and everyone's life would be easier if it was recognized as such.

My current understanding is that the notion of "standalone token" as currently somewhat-specified (you have to read a lot between the lines already) is not such a good fit for "we want the nice whitespace behavior a human would expect"; it is doing okay for existing constructs (although arguably `{{#foo}}{{#bar}}` should *already* be treated as standalone, don't we think?), and slightly worse for this new construct which introduces these parameter blocks that are sometimes in invisible/non-rendered position. This is life, we cannot have all things perfect, and I think it should be discussed separately.

2021-03-19 11:57 UTC, jgonggrijp commented
@gasche Thank you for taking the effort to have this interesting discussion with me.

Regarding terminology, point taken. I should mention that my opinion is not so strong that I believe it should block merging. I would like to see it be more consistent, but since the terminology is not going to change the syntactical or semantical content of the specs, we are going to get the same result in the end and I'll have the same work to do in my own implementation.

For academic interest, I'll mention that parametric partials behave exactly like functions with default arguments. Indeed, nested function calls with defaults along the chain will give the same behavior where the outermost caller wins. On the other hand, a template that calls multiple (parametric) partials behaves more like composition than like multiple inheritance, when looking from an OOP perspective. Partials might be deeply nested within sections from the "inheriting" template, giving it complete control to wrap and organize the partials however the author wants. In OOP, inheritance generally isn't that flexible but composition is.

Regarding whitespace, I think I actually prefer the whitespace handling as it is currently specified, although I agree that `{{#section}}{{#nested}}` should ideally be recognized as two standalone tags. I would agree to moving that discussion to a separate issue.

@Danappelxx @spullara I could prepare a continuation PR that renames the spec to start with a `~` (to mark it as optional) and that makes the terminology more consistent (without necessarily enforcing one particular jargon). Would you welcome that?

2021-03-21 14:00 UTC, gasche commented
> I could prepare a continuation PR that renames the spec to start with a ~ (to mark it as optional) and that makes the terminology more consistent (without necessarily enforcing one particular jargon).

Personally I think this would be a good idea. Thanks for your active contributions to the mustache spec!

2021-03-27 00:03 UTC, bubach commented
Sigh.. I  was planning on letting this one go, but I....simply can't wrap my head around it. _Why...?_  

I mean, besides the fact that it's not really needed? ...I mean - any solution worth a damn either does view and/or layout composition; translations and such to the data before it leaves the backend...

_or_
 
 even better  - have the vue / web-component's initi() or onload() funktion do final checks and possible formatting calls for the raw api data right before dom-rendering  of the widget.

The projects freaking tag-line even reads: "Mustache is a "logic-less" templating language."

So, eh  whats up?  Did you end up here  av misstake while looking for any of these perhaps, sounds more like your thing:

  Smarty 
  Twig,
  Razor
  Platesphp,
  Blade,
  php-TAL
  
  I mean.. shit... should just have forked & unfollowed.. Gn.. 😓

2021-04-21 02:18 UTC, Danappelxx commented
Closing in favor of #125, which looks like it will be merged soon - further comments should be added there. Thank you to everyone for facilitating a healthy discussion.

2021-04-21 02:18 UTC, closed without merging